version: '3.9'

services:
  api:
    env_file: .env
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./api:/api
    command: >
      sh -c 'cd /api && python manage.py createsuperuser && python3 manage.py
      makemigrations && python3 manage.py migrate && python3 manage.py runserver
      0.0.0.0:8000'
volumes:
  api:
