# Generated by Django 3.2.12 on 2022-03-06 22:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_1', models.EmailField(max_length=254, unique=True)),
                ('phone_1', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('address_one', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address_two', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=32)),
                ('contact_1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contact')),
            ],
            options={
                'unique_together': {('username', 'contact_1')},
            },
        ),
    ]
