# Generated by Django 4.0.3 on 2022-03-02 20:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.meta')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.meta')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.person')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_1', models.EmailField(max_length=254)),
                ('phone_1', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('address_one', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address_two', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.meta')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demo.person')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('contact_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.contact')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.meta')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.user')),
            ],
        ),
    ]
