# Generated by Django 4.0.3 on 2022-03-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_account_meta_alter_contact_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_1',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
