# Generated by Django 4.0.3 on 2022-03-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_contact_email_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.meta'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.meta'),
        ),
        migrations.AlterField(
            model_name='person',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.meta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.meta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demo.person'),
        ),
    ]
